language: node_js
before_install:
- npm install -g grunt-cli
- bundle install
env:
  global:
  - secure: JW6DF1fCv3qFSYlMnH7Q4FzGCOgPWwjul77DwCL3u5MU6wNda+q7ErGASLSStyNVCX8R78eU+71v5c+VZ6NQ54P3xCcS0Ut/ZA9B468H80B+xZkHqGbactmYULWCa/+fUHHxRNC3Jq3nJ6FrRSAQF7y29ii+J/xL4d8gBA0JpB8=
  - secure: W7SIHF8oUoxjAr8a8HDv+UM4uIKUmuj9eAuB3AkGjyxLeIIO/tPHQ2yFx8tEtTqXWNnuve7AvnIAD6PmG67VvXBvESGRXxe7nH4qRCclDScfWahzxLdZyGbhMO742mjr/dItrtwUTo8T/T7wam6yTg4xVN4ukxJyu7v5i8aqN+c=
