language: node_js
before_install:
- npm install -g grunt-cli
- gem install sass
env:
  global:
    - secure: Jui6UzQnjUzmDE14YCuTdo4lzu5Z7Z5Z7Jo+ORt6CZlu3kYpPOxNaxxmv6NNZ2uFRl1jz7gvYnmBKGDWPeaS9xdKY7wLGEDpj8hs67hV0X0LiqY4YYhwn0VwPHfuzlADD4cKcoKDJD7wilggyd0s1yNyb1ocIOem7t/BXFcyI2I=
    - secure: kxTkNYUM1srfewf7A+uSpd32JT4PHfhcEH+lZkxClkjb4y8cvqpeM3Yq/Icv5wRWskQpcfa0A8HmCvqE4vuZDGsyrcLCmqvlXvG0aHyQJp7D62+HtgxkPLyFNNMa4i397Q+SrAyNUKxg6M5TVfTqXfb/gjXofC+90fFWi5wsefM=
    - secure: hWqA+K/8ZAOBJYBaWvw1vmih0rIUVwmQJ/4F1gqHZQkW+e1vSAn9JPZ/DhrMEAPRT8N9v4Z53Y5kdjpUEQpdOvZFQqOGf6uo/FbIZBIkc7J8xfLgA7te0kmvgxrNgcgVytZvNWcRHGeDYZhb40kbiESOdM2/U3Je7I50/InS4DA=
